### ISSUE TITLE
Broken for reflector

### ISSUE THREAD

**Issue by raykrist** [TorLdre/puppet-calico#6]
Since param.pp have
`$compute_manage_bird_config = true`
and
`$reflector_manage_bird_config = true`

you will never be able to use the reflector templates her:
https://github.com/beddari/puppet-calico/blob/master/manifests/bird.pp#L12-L19

You could use `calico::compute::manage_bird_config` and `calico::reflector::manage_bird_config` in the if-statment above. Then you could override the default values in e.g. hieradata.

**Comment by beddari** [comment]
Tried fixing this in 1f7b8db8c8492664df20695b1bf347184866306e

**Comment by beddari** [comment]
An even better fix would be to remove the role-specific bird config file resources and refactor them to be (possibly external) defines. I'll make a note to remember that for the future.

**Comment by beddari** [comment]
Fixed in #9 ... a real fix would be a refactor to using a define like described above and in #8
